language: python

script:
  - python3 tests/pld-test.py tests/tests/Init/
  - [[ python3 tests/pld-test.py tests/tests/Init/ =~ "TEST FAIL" ]] || exit 1;
  - python3 tests/pld-test.py tests/tests/Affectation/
  - [[ python3 tests/pld-test.py tests/tests/Affectation/ =~ "TEST FAIL" ]] || exit 1;