language: python

services:
  - docker

before_install:
  - docker run --rm --name pld-comp -v "$(pwd)":/pld-comp -t -d -w /pld-comp eguerin/antlr4cpp

script:
  - if [[ $(docker exec pld-comp bash -c "cd compiler; make; cd ../tests; ./test_if.sh") =~ "TEST FAIL" ]]; then
      exit 1;
    fi