language: python

services:
  - docker

before_install:
  - docker run --rm --name pld-comp -v "$(pwd)":/pld-comp -t -d -w /pld-comp eguerin/antlr4cpp
  - docker exec -it pld-comp bash /bin/sh -c "cd compiler/; make; cd ..; python3 tests/pld-test.py tests/tests;
  if [[ python3 tests/pld-test.py tests/tests =~ "TEST FAIL" ]]; then exit 1; fi"

script:
  - cd compiler/
  - make
  - cd ..
  - python3 tests/pld-test.py tests/tests
  - if [[ python3 tests/pld-test.py tests/tests =~ "TEST FAIL" ]]; then
      exit 1;
    fi